---
kind: pipeline
name: default

steps:
  - name: slack notification on start
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      template: >
        {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} start: {{build.link}}
    when:
      branch:
        - mstdn-asterism-xyz
        - master

  - name: build mstdn-asterism-xyz image
    image: plugins/docker
    settings:
      repo: orlea/mastodon
      tag: mstdn-asterism-xyz
      username:
        from_secret: dockerhub_id
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - mstdn-asterism-xyz

  - name: build latest image
    image: plugins/docker
    settings:
      repo: orlea/mastodon
      tag: latest
      username:
        from_secret: dockerhub_id
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master

  - name: build tagged image
    image: plugins/docker
    settings:
      repo: orlea/mastodon
      auto_tag: true
      username:
        from_secret: dockerhub_id
      password:
        from_secret: dockerhub_password
    when:
      event:
        - tag

  - name: slack notification on complete
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      template: >
        {{#success build.status}}
          {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} succeeded: {{build.link}}
        {{else}}
          {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} failed: {{build.link}}
        {{/success}}
    when:
      branch:
        - mstdn-asterism-xyz
        - master
      status:
        - success
        - failure